Should be working but...
java.lang.NoClassDefFoundError: mc3kit/graphical/ptree/TopologyVariable
	at mc3kit.graphical.GraphicalModel.initialize(GraphicalModel.java:117)
	at mc3kit.MCMC.initializeChains(MCMC.java:160)
	at mc3kit.MCMC.initialize(MCMC.java:146)
	at mc3kit.MCMC.run(MCMC.java:247)
	at seasmig.SeasonalMigrationMain.main(SeasonalMigrationMain.java:120)
Caused by: java.lang.ClassNotFoundException:
mc3kit.graphical.ptree.TopologyVariable
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
	... 5 more